# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Klinisk erfaring"
  url = "#clinical-experience"
  weight = 10

[[main]]
  name = "Annen erfaring"
  url = "#other-experience"
  weight = 20

[[main]]
  name = "Prosjekter"
  url = "#projects"
  weight = 30

# [[main]]
#   name = "Talks"
#   url = "#talks"
#   weight = 40

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 50

[[main]]
  name = "Kontaktinformasjon"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "media/resume.pdf"
   weight = 70
